remember_me: "1"
minimum_value: 1
per_page_value: 10
increase_quantity: 1
minimum_inventory: 0
zero_value: 0
cart_value: 0
total: 0
time_expire: 2
user:
  name:
    maximum: 50
  email:
    maximum: 255
  per_page: 5
password:
  minimum: 6

product:
  name:
    maximum: 100
  description:
    maximum: 255
  image:
    size: 400
    thumb_size: 200
category:
  list_size: 5
